### ISSUE TITLE
[gl-react-native] freezes with no logs

### ISSUE THREAD

**Issue by superandrew213** [gre/gl-react#90] opened 2017-03-28 08:05 UTC
#### library version
`react-native@0.42.3`
`gl-react@3.0.0-alpha.5`
`gl-react-native@3.0.0-alpha.5`

#### Steps to reproduce the behavior

Trying to get this https://gl-react-cookbook.surge.sh/saturation to work on react-native.

When I `npm i` it installs `gl-react@3.0.0-alpha1`. 
When I run the project, I get the following:
```
Possible Unhandled Promise Rejection (id: 0):
getPixelSize is not a function. (In 'getPixelSize(props)', 'getPixelSize' is undefined)
```

When I manually install `gl-react@3.0.0-alpha.5` app freezes with no logs.

This is my code:
```
import React, { Component } from "react";
import { View } from 'react-native';
import { Shaders, Node, GLSL } from "gl-react";
import { Surface, Image } from "gl-react-native";

const shaders = Shaders.create({
  Saturate: {
    frag: GLSL`
precision highp float;
varying vec2 uv;
uniform sampler2D t;
uniform float contrast, saturation, brightness;
const vec3 L = vec3(0.2125, 0.7154, 0.0721);
void main() {
  vec4 c = texture2D(t, uv);
	vec3 brt = c.rgb * brightness;
	gl_FragColor = vec4(mix(
    vec3(0.5),
    mix(vec3(dot(brt, L)), brt, saturation),
    contrast), c.a);
}
`
  }
});

export const Saturate = ({ contrast, saturation, brightness, children }) =>
  <Node
    shader={shaders.Saturate}
    uniforms={{ contrast, saturation, brightness, t: children }}
  />;

export default class extends Component {
  render() {
    return (
      <Surface width={480} height={300}>
        <Saturate contrast={1} saturation={1} brightness={1}>
          {/* <Image source={{ uri: 'https://i.imgur.com/uTP9Xfr.jpg' }} width={480} height={300} />*/}
          https://i.imgur.com/uTP9Xfr.jpg
        </Saturate>
      </Surface>
    );
  }
}
```

**Comment by gre** [comment] 2017-03-28 09:29
thanks for the report,

I need to improve how errors get handled because it looks like they are thrown silently from inside gl-react ..

a current limitation of the alpha is that you need to use exact same version (gl-react@alpha.5 with gl-react-native@alpha.5) – actually I probably should release the 'alpha' under `@next` so it's always in sync..

for the bug, i'll need to reproduce, weird thing is that I have it working inside `cookbookrn` app:

![screen shot 2017-03-28 at 11 29 07](https://cloud.githubusercontent.com/assets/211411/24398456/c63d5952-13a9-11e7-8ab0-7bf987d17f20.png)


Do you have multiple surface at the same time? I think there is currently a bug around that in EXGL implementation and we'll need to get it fixed.

**Comment by superandrew213** [comment] 2017-03-29 01:10
I tried running the `cookbook-rn` but it doesn't work. It has dependencies:
```
"gl-react": "^3.0.0-alpha.3",
"gl-react-native": "^3.0.0-alpha1",
```
I like the `@next` idea.

I updated those to 3.0.0-alpha.5. The saturation screen works in cookbook-rn but when I go to colorscale screen it freezes like on my project with no logs.

Don't have multiple surfaces. I copy and pasted the exact saturation code from cookbook-rn into my project but still freezes as soon as I access the screen.

**Comment by gre** [comment] 2017-03-29 06:41
looks like the dep of cookbook-rn is wrong, I have a script that copy manually the packages/* projects into coobook-rn but it's a bad idea and i'll try to get things more ready ^^

Mmh there must be something wrong that makes this example to freeze. One guess is that the JS is going faster than the GL implementation to catch up unqueueing jobs (the gl context calls are currently just stacking and the webgl unqueue them). I had a chat with @nikki93 (who implemented the C++ WebGL abstraction) and told me we probably should introduce something like a `requestGLFrame` so the implementation could "slow down" the JS loop when it can't follow. the gl-react lib would just use that instead of currently using requestAnimationFrame

**Comment by gre** [comment] 2017-03-29 07:02
BTW there are a few examples that currently reliably crash like you noticed in your app, i've noted it in the TODO list https://github.com/gre/gl-react/blob/master/packages/gl-react-native/TODO#L7

really need to hunt down this todo list before assuming this v3 is stable

**Comment by nikki93** [comment] 2017-03-29 09:00
Ok awesome. Will try to run this repro case and track this down. Does it happen on Simulator too for you?

**Comment by gre** [comment] 2017-03-29 09:06
yeah I'll try to implement that requestGLFrame just to see if it solves the problem. if it doesn't, it's something else!

**Comment by superandrew213** [comment] 2017-03-29 09:13
@nikki93 I've only tested it on the sim so far

**Comment by gre** [comment] 2017-03-29 09:17
for some reason the GL implementation is quite slow on sim' and it might raise the "can't catch up" problem more often. (but it's pure speculation)

**Comment by superandrew213** [comment] 2017-03-29 09:30
I just tested my project and `cookbook-rn` on device. My project doesn't freeze anymore but image doesn't load. `cookbook-rn` colorscale screen still freezes.

**Comment by nikki93** [comment] 2017-04-04 23:46
Tried on device and the image loads for me. 🤔 Are you still having this problem @superandrew213 ?

**Comment by gre** [comment] 2017-04-09 09:24
I can reproduce a crash when starting cookbook-rn and colorscale example both on Simulator (tested on iPhone6 sim', in Debug mode) and on device (iPhone 6, in Release mode!)

**Comment by gre** [comment] 2017-04-20 09:17
i'm going to review that again because there might be something weird happening in that cookbook-rn.. I can make it crash in the cookbook-rn but not cookbook-expo. weird!

**Comment by gre** [comment] 2017-04-30 21:05
it looks like it's related to the fact 2 Surface renders at the time. If I disable either the "color map overflow" rendering or the example itself it's fine. But both rendered at same time breaks..

I suspect something weird around multi-glview support. see #103

**Comment by gre** [comment] 2017-05-07 13:45
in the cookbook-rn (and -expo) i've written some "tests" at the end that stress-test some part of the lib. One is called "many" and tries to create 64 GLView of 8x8 . you can notice things takes a lot of time to render and it then became non responsive (like the whole UI is blocked, can't go back). on iOS (device) it even stops the navigator transition until all tiles are rendered (for like 30s-1min), then you can do a back, which also freeze for like 10s (probably because the unmount).

colorscale still seem to freeze **only on iOS** for unknown reason.

see on https://expo.io/@gre/gl-react

**Comment by gre** [comment] 2017-05-07 14:04
you can also try the example "Hearts" , it freezes forever on iOS , but works "ok" on Android. this involves creating a few GLView (initially 3, then it's supposed to append some when you scroll, as it's a ListView). it still crashes on Android after a bit on scroll, (maybe reach some Android limitation on max concurrent gl views? )

**Comment by gre** [comment] 2020-01-01 15:33
I think it's fixed now.

**Closed by gre** 2020-01-01 15:33 UTC
Labels: bug, help wanted
