### ISSUE TITLE
White screen after changing Surface width/height in gl-react-native

### ISSUE THREAD

**Issue by QuevedoIB** [gre/gl-react#228] opened 2020-01-14 21:27 UTC
"gl-react": "^4.0.1",
"gl-react-image": "^3.1.1",
"gl-react-instagramfilters": "^0.2.0",
"gl-react-native": "^4.0.1",

Latest version of gl-react and gl-react-native.

#### Expected behavior

Changing Surface style (height and width) should change sizes and rerender.

#### Actual behavior

Surface randomly disappears after changing the sizes.

#### Steps to reproduce the behavior

Change state and pass different props to Surface component.

Anyone had a similar problem and has any idea of what could be the reason?

**Comment by gre** [comment] 2020-01-19 16:45
I wrote a test example in cookbook-rn "resizing" and manage to reproduce something weird. I have a slider that control the surface size, and strangely the canvas manage to re-render only have of the time. I wonder if it's some inner properties of Expo GLView that defer a bit the re-rendering and therefore empty the canvas content a bit after the react updates.

any clue @nikki93 ?

**Comment by QuevedoIB** [comment] 2020-02-04 10:19
Any update on this? @gre @nikki93 @sjchmiela

**Comment by gre** [comment] 2020-12-27 12:27
I'll close this in favor of https://github.com/gre/gl-react/issues/288 because it's a more up to date version of the current situation on latest expo (it no longer resize at all)

**Closed by gre** 2020-12-27 12:27 UTC
Labels: Expo
